"""empty message

Revision ID: 38042f03222e
Revises: 
Create Date: 2024-03-30 20:31:11.607640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38042f03222e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('account_verified', sa.Boolean(), nullable=True),
    sa.Column('pin', sa.String(length=4), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bank_account',
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('bank_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=126), nullable=False),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_account')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
