"""empty message

Revision ID: 680393689dff
Revises: 38042f03222e
Create Date: 2024-03-30 20:55:30.299670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680393689dff'
down_revision = '38042f03222e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
